# Generated by Django 5.2.6 on 2025-09-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
